### ISSUE TITLE
Lines not showing with update

### ISSUE THREAD

**Issue by Petra105** [Drahsid/TargetLines#2]
Targetlines are not showing with the update that was pushed to testing.

**Comment by Drahsid** [comment]
Works for me and others I have seen. Additionally, there is no 'testing' version of TargetLines. The only version of the plugin on the official repo is in the stable channel.

- Is Dalamud up to date?
- Is there anything in the log?

**Comment by Petra105** [comment]
Yes Dalamud is up to date, and nothing in the log related to targetlines, pretty much just listings of out of date plugins. Is there an in game setting that would conflict with targetlines? maybe a display setting or something?

**Comment by Petra105** [comment]
Nevermind I am dumb. I didn't realize it was toggled off when it updated. I never tried just /ttl -_-
