### ISSUE TITLE
[Request] Focus target filter

### ISSUE THREAD

**Issue by kaedys** [Drahsid/TargetLines#3]
When tanking instances, I very commonly keep my healer focused, and vice versa when I'm healing.  It'd be nice if I could use "focus target" as a filter for a line to facilitate that, so I can more easily keep track of my focus target.  (I know I could do by role, but then I have them around when I'm DPSing, and also multiple in 8-mans and such).

Actually, come to think of it, "target" as a filter would be nice as well.  As in, I could set source filter "target", target filter "player", and get a line when I target an NPC pointing at whom that NPC is attacking, _without_ getting lines for _all_ NPCs at once (like is the case if source filter is simply "enemy").  Maybe "target enemy" and "target ally", to better differentiate for lines like that.

**Comment by Drahsid** [comment]
I'm not sure I understand your request.
Do you want to filter focus targets as well as normal targets?

**Comment by kaedys** [comment]
So, two asks here.  The primary one is that I'd like to be able to draw a line from myself to my focus target, so I can keep track of them easier.  This is handy for keeping track of my tank or healer in a dungeon, my partner tank or healer in an 8-man, my dance partner on DNC, my Aetherial Manipulation default target on BLM, etc.  I already use focus targeting heavily for this purpose, since it lets me track their HP, buffs, and cast bars, but it can be quite easy to miss the little blue arrow over their when there are target markers and VFX going on (especially since it's quite similar to the target arrow), so being able to draw a line from myself to them would help with that.

And then secondarily, it'd be nice to be able to draw a line from my current target to _their_ target.   Specifically , if I set up lines for source "enemy", target "player", it shows a line from every single enemy NPC toward who they are targeting, but that can get very noisy when there's a lot of enemies on the screen.  If instead I could draw a line from _only_ my current target to whatever they were targeting, that would trim it down and let me more easily see, for example, who the boss is preparing to flatten.  This part of the request is definitely secondary, though, and I thought it up while writing the initial request and decided to throw it in as well.

I hope all that makes sense.

**Comment by Drahsid** [comment]
Just an update, I am working on implemented focus target filters (should be in the next update,) though I don't believe your second request will be reasonable to implement with how things work right now.

**Comment by kaedys** [comment]
Fair enough.  The focus target one will provide a lot of benefit on its own, so _much_ appreciate that.

**Comment by Drahsid** [comment]
Pushed this to the repo in commit [df0fe72bb40bf727798d6359a37f3701d7b21168](https://github.com/Drahsid/TargetLines/commit/df0fe72bb40bf727798d6359a37f3701d7b21168). When it's approved for dalamud, you should see an update to 1.7.1 which includes a toggle in the line filters for "Focus Target". Keep in mind that if "Focus Target" is toggled, the filter will not apply to entities which are not focus-targeted, and vice-versa..
