### ISSUE TITLE
Targetlines throwing errors and not showing unless legacy mode.

### ISSUE THREAD

**Issue by Petra105** [Drahsid/TargetLines#5]
https://i.gyazo.com/63c097546d3f25702953f8af53583722.png
Getting my log filled with these errors repeatedly.

**Comment by Petra105** [comment]
Edit, got around it by disabling and reenabling the plugin. Not sure what caused it in the first place.

**Comment by Drahsid** [comment]
See issue #4, this is already fixed on my end, and will not be an issue on the next update. 
To reiterate the current solution: ensure your minimum sample count is no less than 3, and your maximum sample count is some greater number that is at least 5, or disable dynamic sample count.
